---
title: "Active Players"
---

This page ranks the top active players. It also shows the best players who have yet to win a Grand Slam.

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  comment = "#", fig.height = 3, 
  cache = FALSE, collapse = TRUE,
  error = TRUE, echo = FALSE,
  message = FALSE,
  warning = FALSE)
```

```{r load, include = FALSE}
library("tidyverse"); theme_set(theme_minimal())
library("here")
library("flextable")
library("plotly")

matches <- read_csv(here("data/gs_matches.csv"))
players <- read_csv(here("data/gs_players.csv"))

set_flextable_defaults(
  font.size = 10, theme_fun = theme_zebra,
  padding = 3,
  background.color = "#EFEFEF",
  text.align = "center")
```

```{r active players}
active <- players %>%
  group_by(name, dob, ioc) %>%
  summarize(
    `Total Points` = sum(points) + sum(bonus),
    `Victory Points` = sum(points),
    `Bonus Points` = sum(bonus),
    Titles = sum(round == "F" & result == "winner"),
    Finals = sum(round == "F"),
    last_tournament = max(date),
    Victories = sum(points > 0),
    Defeats = sum(points < 0),
    `Win Percent` = scales::percent(Victories/(Victories + Defeats), accuracy = .01)) %>%
  ungroup() %>%
  filter(last_tournament > ymd(20230101), name != "Andy Murray", name != "Rafael Nadal") %>%
  rename(
    Country = ioc,
    Player = name) %>%
  arrange(desc(`Total Points`)) %>%
  mutate(
    Rank = row_number(),
    `Birth Year` = year(dob)) %>%
  relocate(Rank, .before = Player) %>%
  relocate(`Birth Year`, .before = Country) %>%
  select(-dob, -last_tournament) %>%
  dplyr::slice(1:25)

active_25 <- active %>% select(Player) %>% pull()

active %>%
  flextable() %>%
  align(align = "center", part = "all") %>%
  width(j = 12, width = 1) %>%
  width(j = 2, width = 2.5) %>%
  width(j = 4, width = 2.1) %>%
  width(j = c(1,4,8:11), width = .6) %>%
  colformat_double(j = c(3,5:9), digits = 0) %>%
  colformat_double(j = 3,
    big.mark = "", digits = 0, na_str = "N/A")
```

```{r,fig.topcaption=TRUE}
#| fig-cap: Active Player Timeline
p <- players %>%
  group_by(name) %>%
  filter(name %in% active_25) %>%
  mutate(
    `Career Points` = cumsum(points + bonus)) %>%
  arrange(name, date) %>%
  rename(
    Country = ioc,
    Date = date,
    Player = name) %>%
  ungroup() %>%
  ggplot(aes(x = Date, y = `Career Points`, color = Player, group = Country)) +
  geom_line() +
  scale_x_date(expand = c(0, 1000)) +
  theme(legend.position = "none")

ggplotly(p)
```

```{r top active players without a grand slam}
#| tbl-cap: Top Active Players without a Grand Slam
players %>%
  group_by(name, dob, ioc) %>%
  summarize(
    `Total Points` = sum(points) + sum(bonus),
    `Victory Points` = sum(points),
    `Bonus Points` = sum(bonus),
    Titles = sum(round == "F" & result == "winner"),
    Finals = sum(round == "F"),
    Victories = sum(points > 0),
    Defeats = sum(points < 0),
    last_tournament = max(date),
    `Win Percent` = scales::percent(Victories/(Victories + Defeats), accuracy = .01)) %>%
  ungroup() %>%
  filter(last_tournament > ymd(20230101), name != "Andy Murray", Titles == 0) %>%
  rename(
    Country = ioc,
    Name = name) %>%
  arrange(desc(`Total Points`)) %>%
  mutate(
    Rank = row_number(),
    `Birth Year` = year(dob)) %>%
  relocate(Rank, .before = Name) %>%
  relocate(`Birth Year`, .before = Country) %>%
  select(-dob, -Titles, -last_tournament) %>%
  dplyr::slice(1:25) %>% 
  flextable() %>%
  align(align = "center", part = "all") %>%
  width(j = 11, width = 1.3) %>%
  width(j = 2, width = 2.2) %>%
  width(j = 4, width = 1.6) %>%
  width(j = c(1,8:10), width = .7) %>%
  colformat_double(j = c(5:9), digits = 0) %>%
  colformat_double(j = 3,
    big.mark = "", digits = 0, na_str = "N/A")
```



