---
title: "Australian Open"
---

Rankings, timeline, and frequent matchups at the Australian Open. The Australian Open is a Hard Court event typically held in January in Melbourne, Australia.

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  comment = "#", fig.height = 3, 
  cache = FALSE, collapse = TRUE,
  error = TRUE, echo = FALSE,
  message = FALSE,
  warning = FALSE,
  fig.topcaption=TRUE)
```

```{r}
library("tidyverse"); theme_set(theme_minimal())
library("here")
library("flextable")
library("plotly")

matches <- read_csv(here("data/gs_matches.csv"))
players <- read_csv(here("data/gs_players.csv"))

set_flextable_defaults(
  font.size = 10, theme_fun = theme_zebra,
  padding = 3,
  background.color = "#EFEFEF",
  text.align = "center")
```

```{r}
#| tbl-cap: Australian Open Rankings

sum <- players %>%
  filter(tourney_name == "Australian Open") %>%
  group_by(name, dob, ioc) %>%
  mutate(championship = if_else(result == "winner" & round == "F", 1, 0)) %>%
  summarize(
    `Total Points` = sum(points) + sum(bonus),
    `Victory Points` = sum(points),
    `Bonus Points` = sum(bonus),
    Titles = sum(championship),
    Finals = sum(round == "F"),
    Victories = sum(points > 0),
    Defeats = sum(points < 0),
    `Win Percent` = scales::percent(Victories/(Victories + Defeats), accuracy = .01)) %>%
  ungroup() %>%
  rename(
    Country = ioc,
    Name = name) %>%
  arrange(desc(`Total Points`)) %>%
  mutate(
    Rank = row_number(),
    `Birth Year` = year(dob)) %>%
  relocate(Rank, .before = Name) %>%
  relocate(`Birth Year`, .before = Country) %>%
  select(-dob)

sum %>%
  slice(1:25) %>%
  flextable() %>%
  align(align = "center", part = "all") %>%
  width(j = 12, width = 1.3) %>%
  width(j = 2, width = 3) %>%
  width(j = 4, width = 2) %>%
  width(j = c(1,8:11), width = .7) %>%
  colformat_double(j = c(5,6,7,8,9), digits = 0) %>%
  colformat_double(j = 3,
    big.mark = "", digits = 0, na_str = "N/A")
```

```{r, fig.height = 7, fig.width = 12}
#| fig.cap: Top 25 Players at Australian Open

# top players over time
top25 <- sum %>% slice(1:25) %>% select(Name) %>% pull()

p <- players %>%
  group_by(name) %>%
  filter(tourney_name == "Australian Open", name %in% top25) %>%
  mutate(
    `Career Points` = cumsum(points + bonus)) %>%
  rename(
    Country = ioc,
    Date = date,
    Player = name) %>%
  ungroup() %>%
  ggplot(aes(x = Date, y = `Career Points`, color = Player, group = Country)) +
  geom_line() +
  scale_x_date(expand = c(0, 1000)) +
  theme(legend.position = "none")

ggplotly(p)
```

```{r}
#| tbl-cap: Most Common Matchups
players %>%
  filter(score != "W/O", tourney_name == "Australian Open") %>%
  group_by(name, opp_name) %>%
  summarize(
    Matchups = n(),
    Wins = sum(result == "winner"),
    Losses = sum(result == "loser"),
    `First Matchup` = year(min(date)),
    `Last Matchup` = year(max(date))) %>%
  ungroup() %>%
  mutate(
    Wins = if_else(name > opp_name, Wins + .01, Wins),
    remove = if_else(Wins > Losses, "keep", "remove")) %>%
  filter(remove == "keep") %>%
  select(-remove) %>%
  arrange(desc(Matchups)) %>%
  filter(Matchups > 2) %>%
  mutate(
    Wins = round(Wins, 0),
    Rank = rank(-Matchups, ties.method = "min")) %>%
  rename(
    `Player 1` = name,
    `Player 2` = opp_name) %>%
  relocate(Rank, .before = `Player 1`) %>%
  flextable() %>%
  align(align = "center", part = "all") %>%
  width(j = c(2,3), 1.8) %>%
  width(j = c(7,8), 1.1) %>%
  width(j = 1, .6) %>%
  colformat_double(j = c(7,8),
                   big.mark = "", digits = 0, na_str = "N/A")
```

```{r table country rank}
#| tbl-cap: All Time Country Rankings
players %>%
  filter(tourney_name == "Australian Open") %>%
  group_by(ioc) %>%
  summarize(
    `Total Points` = sum(if_else(points > 0 , points, 0)) + sum(bonus),
    `Victory Points` = sum(if_else(points > 0 , points, 0)),
    `Bonus Points` = sum(bonus),
    Titles = sum(result == "winner" & round == "F"),
    Finals = sum(round == "F"),
    Victories = sum(points > 0),
    `Win Percent` = scales::percent(sum(points > 0)/(sum(points > 0) + sum(points < 0)), accuracy = .01)) %>%
  ungroup() %>%
  rename(
    Country = ioc) %>%
  arrange(desc(`Total Points`)) %>%
  mutate(
    Rank = row_number()) %>%
  relocate(Rank, .before = Country) %>%
  slice(1:25) %>%
  flextable() %>%
  align(align = "center", part = "all") %>%
  width(j = 1, width = .6) %>%
  width(j = c(3:5, 9), width = 1.2) %>%
  colformat_double(j = c(3:5), digits = 0) %>%
  width(j = 2, width = 2)
```

```{r, fig.height = 7, fig.width = 12}
#| fig-cap: Countries over Time
aus_co_sum <- players %>%
  filter(tourney_name == "Australian Open") %>%
  group_by(ioc) %>%
  summarize(
    `Total Points` = sum(if_else(points > 0 , points, 0)) + sum(bonus)) %>%
  ungroup() %>%
  arrange(desc(`Total Points`))

top25 <- aus_co_sum %>% ungroup() %>% slice(1:25) %>% select(ioc) %>% pull()

# top players over time
p <- players %>%
  filter(tourney_name == "Australian Open") %>%
  mutate(points_revision = if_else(points > 0, points, 0)) %>%
  group_by(ioc) %>%
  mutate(
    `Total Points` = cumsum(points_revision + bonus)) %>%
  filter(ioc %in% top25) %>%
  rename(
    Country = ioc,
    Date = date) %>%
  ungroup() %>%
  ggplot(aes(x = Date, y = `Total Points`, color = Country)) +
  geom_line() +
  scale_x_date(expand = c(0, 1000)) +
  theme(legend.position = "none")

ggplotly(p)
```
