# Player Birthplace and age

# load in data
library("tidyverse")
library("janitor")
library("here")
library("plotly")
library("tidygeocoder")

path_to_file <- here("data")

players_info <- read_csv(here("data/atp_players.csv")) %>%
  mutate(player = str_c(name_first, " ", name_last)) %>%
  select(-contains("name"), -wikidata_id)

files_rankings <- fs::dir_ls(path = path_to_file, glob = "*atp_ranking_*csv")

rankings <- read_csv(files_rankings, id = "path") %>%
  rename(player_id = player) %>%
  mutate(date = ymd(ranking_date)) %>%
  select(-path, -points, -ranking_date) %>%
  left_join(players_info, by = join_by(player_id)) %>%
  arrange(date, rank)

last_issue <- rankings %>%
  select(date) %>%
  distinct() %>%
  mutate(year = year(date)) %>%
  group_by(year) %>%
  summarize(date = max(date)) %>%
  select(date) %>% pull()


# Data Collection ---------------------------------------------------------

rankings_100 <- rankings %>% filter(date %in% last_issue, rank < 101) %>%
  relocate(player, .before = player_id) %>%
  rename(rank_date = date) %>%
  relocate(rank_date, .before = rank) %>%
  mutate(
    dob = ymd(dob),
    age = time_length(rank_date - dob, "years")) %>%
  mutate(
    birth_lat = case_when(
      player == "Novak Djokovic" ~ 44.8178131,
      player == "Carlos Alcaraz" ~ 37.94133758544922,
      player == "Jannik Sinner" ~ 46.7328719,
      player == "Daniil Medvedev" ~ 55.7505412,
      player == "Andrey Rublev" ~ 55.7505412,
      player == "Stefanos Tsitsipas" ~ 39.4899739,
      player == "Alexander Zverev" ~ 53.550341,
      player == "Holger Rune" ~ 55.7535946,
      player == "Hubert Hurkacz" ~ 51.1089776,
      player == "Taylor Fritz" ~ 32.7174202,
      player == "Casper Ruud" ~ 59.9133301,
      player == "Alex De Minaur" ~ -33.8698439,
      player == "Tommy Paul" ~ 39.8512162,
      player == "Grigor Dimitrov" ~ 41.763101,
      player == "Karen Khachanov" ~ 55.7505412,
      player == "Frances Tiafoe" ~ 38.9529442 ,
      player == "Ben Shelton" ~ 33.7489924,
      player == "Cameron Norrie" ~ -26.205,
      player == "Nicolas Jarry" ~ -33.4377756,
      player == "Ugo Humbert" ~ 49.1196964,
      player == "Francisco Cerundolo" ~ -34.6073387,
      player == "Adrian Mannarino" ~ 48.9875044,
      player == "Tallon Griekspoor" ~ 52.3837058,
      player == "Sebastian Korda" ~ 27.4989278,
      player == "Jan Lennard Struff" ~ 51.4458105,
      player == "Alejandro Davidovich Fokina" ~ 36.7162109,
      player == "Lorenzo Musetti" ~ 44.0771026,
      player == "Sebastian Baez" ~ -34.6073387,
      player == "Felix Auger Aliassime" ~ 45.5031824,
      player == "Tomas Martin Etcheverry" ~ -34.9206797,
      player == "Jiri Lehecka" ~ 50.4116187,
      player == "Alexander Bublik" ~ 59.5706273,
      player == "Laslo Djere" ~ 45.9312407,
      player == "Christopher Eubanks" ~ 33.7489924,
      player == "Aslan Karatsev" ~ 43.024593,
      player == "Arthur Fils" ~ 48.6137157,
      player == "Borna Coric" ~ 45.8130967,
      player == "Daniel Evans" ~ 52.4796992,
      player == "Roman Safiullin" ~ 55.4308841,
      player == "Alexei Popyrin" ~ -33.8698439,
      player == "Mackenzie Mcdonald" ~ 37.8708393,
      player == "Andy Murray" ~ 55.861155,
      player == "Sebastian Ofner" ~ 47.4121987,
      player == "Matteo Arnaldi" ~ 43.8198253,
      player == "Max Purcell" ~ -33.8698439,
      player == "Lorenzo Sonego" ~ 45.0677551,
      player == "Yoshihito Nishioka" ~ 34.7341973,
      player == "Alexander Shevchenko" ~ 47.2610441,
      player == "Stan Wawrinka" ~ 46.5218269,
      player == "Botic Van De Zandschulp" ~ 51.9663016,
      player == "Yannick Hanfmann" ~ 49.0068705,
      player == "Dusan Lajovic" ~ 44.8178131,
      player == "J J Wolf" ~ 39.1014537,
      player == "Miomir Kecmanovic" ~ 44.8178131,
      player == "Jordan Thompson" ~ -33.8698439,
      player == "Daniel Altmaier" ~ 51.3642126,
      player == "Roberto Bautista Agut" ~ 39.9860347,
      player == "Zhizhen Zhang" ~ 31.2323437,
      player == "Marton Fucsovics" ~ 47.9557802,
      player == "Marcos Giron" ~ 34.1705609,
      player == "Jack Draper" ~ 51.3574644,
      player == "Aleksandar Vukic" ~ -33.8698439,
      player == "Roberto Carballes Baena" ~ 28.467178,
      player == "Fabian Marozsan" ~ 47.4978789,
      player == "Thanasi Kokkinakis" ~ -34.9281805,
      player == "Nuno Borges" ~ 41.2373456,
      player == "Pavel Kotov" ~ 55.7505412,
      player == "Christopher Oconnell" ~ -33.8698439,
      player == "Pedro Cachin" ~ -32.6300707,
      player == "Rinky Hijikata" ~ -33.8698439,
      player == "Borna Gojo" ~ 43.5116383,
      player == "Benjamin Bonzi" ~ 43.8374249,
      player == "Gael Monfils" ~ 48.8588897,
      player == "Taro Daniel" ~ 40.7127281,
      player == "Richard Gasquet" ~ 43.3426562,
      player == "Dominik Koepfer" ~ 48.0512198,
      player == "Tomas Machac" ~ 49.9640292,
      player == "Thiago Seyboth Wild" ~ -24.5,
      player == "Bernabe Zapata Miralles" ~ 39.4697065,
      player == "Alexandre Muller" ~ 48.927439,
      player == "Cristian Garin" ~ -18.4785288,
      player == "Juan Pablo Varillas" ~ -12.0621065,
      player == "Gregoire Barrere" ~ 48.8033057,
      player == "Alejandro Tabilo" ~ 43.6534817,
      player == "Jaume Munar" ~ 39.3543115,
      player == "Constant Lestienne" ~ 49.8941708,
      player == "Federico Coria" ~ -32.9593609,
      player == "Albert Ramos" ~ 41.3828939,
      player == "Luca Van Assche" ~ 50.8430448,
      player == "Maximilian Marterer" ~ 49.453872,
      player == "Matteo Berrettini" ~ 41.8933203,
      player == "Daniel Elahi Galan" ~ 7.1255169,
      player == "Dominic Stricker" ~ 46.8739775,
      player == "Facundo Diaz Acosta" ~ -34.6073387,
      player == "Arthur Rinderknech" ~ 43.2291533,
      player == "Alex Michelsen" ~ 33.5761376,
      player == "Dominic Thiem" ~ 47.8131847,
      player == "Yosuke Watanuki" ~ 35.8616402,
      player == "Quentin Halys" ~ 48.9031,
      player == "Emil Ruusuvuori" ~ 60.1674881,
      player == "Rafael Nadal" ~ 39.5696458,
      player == "Robin Soderling" ~ 58.416667,
      player == "Roger Federer" ~ 39.5696458,
      player == "Tomas Berdych" ~ 49.470359802246094,
      player == "David Ferrer" ~38.7893804,
      player == "Andy Roddick" ~ 41.2587459,
      player == "Fernando Verdasco" ~ 40.4167047,
      player == "Mikhail Youzhny" ~ 55.625578,
      player == "Jurgen Melzer" ~ 48.2083537,
      player == "Jo-Wilfried Tsonga" ~ 48.0073849,
      player == "Marin Cilic" ~ 43.9649515,
      player == "Nicolas Almagro" ~ 37.9923795,
      player == "Mardy Fish" ~ 44.8897027,
      player == "Ivan Ljubicic" ~ 44.774688720703125,
      player == "Sam Querrey" ~ 37.7792588,
      player == "John Isner" ~ 36.0726355,
      player == "Marcos Baghdatis" ~ 34.6852901,
      player == "Nikolay Davydenko" ~ 48.9478698,
      player == "Michael Llodra" ~ 48.8588897,
      player == "Ernests Gulbis" ~ 56.9493977,
      player == "Albert Montanes" ~ 40.6178149,
      player == "Juan Monaco" ~ -37.3282887,
      player == "David Nalbandian" ~ -31.2339887,
      player == "Viktor Troicki" ~ 44.8178131,
      player == "Juan Carlos Ferrero" ~ 38.8208523,
      player == "Thomaz Bellucci" ~ -22.4133188,
      player == "Feliciano Lopez" ~ 39.8560679,
      player == "Guillermo Garcia Lopez" ~ 39.20702,
      player == "Philipp Kohlschreiber" ~ 48.3690341,
      player == "Yen Hsun Lu" ~ 24.99111557006836,
      player == "Andrey Golubev" ~ 48.8176,
      player == "Florian Mayer" ~ 49.9427202,
      player == "Juan Ignacio Chela" ~ -34.6073387,
      player == "Jarkko Nieminen" ~ 60.566667,
      player == "Denis Istomin" ~ 41.3123363,
      player == "Gilles Simon" ~ 43.7009358,
      player == "Marcel Granollers" ~ 41.3828939,
      player == "Thiemo De Bakker" ~ 52.0799838,
      player == "Julien Benneteau" ~ 46.2051192,
      player == "Jeremy Chardy" ~ 43.2957547,
      player == "Sergiy Stakhovsky" ~ 50.4500336,
      player == "Potito Starace" ~ 41.2476307,
      player == "Alexandr Dolgopolov" ~ 50.4500336,
      player == "Janko Tipsarevic" ~ 44.8178131,
      player == "Tommy Robredo" ~ 41.7451889,
      player == "Victor Hanescu" ~ 44.4361414,
      player == "Andreas Seppi" ~ 46.4984781,
      player == "Benjamin Becker" ~ 49.4427023,
      player == "Lleyton Hewitt" ~ -34.9281805,
      player == "Fabio Fognini" ~ 43.8198253,
      player == "Daniel Gimeno Traver" ~ 39.4697065,
      player == "Philipp Petzschner" ~ 49.9427202,
      player == "Michael Berrer" ~ 48.7784485,
      player == "Mikhail Kukushkin" ~ 48.7081906,
      player == "Xavier Malisse" ~ 50.8276429,
      player == "Kevin Anderson" ~ -26.205,
      player == "Radek Stepanek" ~ 49.8542719,
      player == "Pablo Cuevas" ~ -31.3972539,
      player == "Santiago Giraldo" ~ 4.8143159,
      player == "Robin Haase" ~ 52.0799838,
      player == "Carlos Berlocq" ~ -35.5786869,
      player == "Tobias Kamke" ~ 53.866444,
      player == "Fernando Gonzalez" ~ -33.4377756,
      player == "Florent Serra" ~ 44.841225,
      player == "Pablo Andujar" ~ 40.0661031,
      player == "Pere Riba" ~ 41.3828939,
      player == "Ivo Karlovic" ~ 45.8130967,
      player == "Eduardo Schwank" ~ -32.9593609,
      player == "Dudi Sela" ~ 33.2074733,
      player == "Ricardo Mello" ~ -22.9056391,
      player == "Ruben Ramirez Hidalgo" ~ 38.3436365,
      player == "Arnaud Clement" ~ 43.5298424,
      player == "Igor Andreev" ~ 55.625578,
      player == "Teymuraz Gabashvili" ~ 41.6934591,
      player == "Illya Marchenko" ~ 48.51134,
      player == "Mischa Zverev" ~ 55.625578,
      player == "Rainer Schuettler" ~ 51.2559045,
      player == "Brian Dabul" ~ -34.6073387,
      player == "Michal Przysiezny" ~ 51.6636791,
      player == "Ricardas Berankis" ~ 54.6870458,
      player == "Ivan Dodig" ~ 43.9649515,
      player == "Lukas Lacko" ~ 48.5895247,
      player == "Marsel Ilhan" ~ 39.6550017,
      player == "Filippo Volandri" ~ 42.7902166,
      player == "Dustin Brown" ~ 52.624056,
      player == "Rui Machado" ~ 37.0162727,
      player == "Leonardo Mayer" ~ -28.9956512,
      player == "Jan Hajek" ~ 49.5940567,
      player == "Marcos Daniel" ~ -28.2550598,
      player == "Paul Henri Mathieu" ~ 48.584614,
      player == "Kei Nishikori" ~ 35.468115,
      player == "Michael Russell" ~ 42.3315509,
      player == "Igor Kunitsyn" ~ 43.1150678,
      player == "Lukasz Kubot" ~ 51.2630333
      ),
    birth_long = case_when(
      player == "Novak Djokovic" ~ 20.4568974,
      player == "Carlos Alcaraz" ~ -1.1545771360397339,
      player == "Jannik Sinner" ~ 12.2791673,
      player == "Daniil Medvedev" ~ 37.6174782,
      player == "Andrey Rublev" ~ 37.6174782,
      player == "Stefanos Tsitsipas" ~ 21.9024738,
      player == "Alexander Zverev" ~ 10.000654,
      player == "Holger Rune" ~ 12.541436,
      player == "Hubert Hurkacz" ~ 17.0326689,
      player == "Taylor Fritz" ~ -117.162772,
      player == "Casper Ruud" ~ 10.7389701,
      player == "Alex De Minaur" ~ 151.2082848,
      player == "Tommy Paul" ~ -74.9619779,
      player == "Grigor Dimitrov" ~ 25.9256255,
      player == "Karen Khachanov" ~ 37.6174782,
      player == "Frances Tiafoe" ~ 76.9408647,
      player == "Ben Shelton" ~ 84.3902644,
      player == "Cameron Norrie" ~ 28.049722,
      player == "Nicolas Jarry" ~ -70.6504502,
      player == "Ugo Humbert" ~ 6.1763552,
      player == "Francisco Cerundolo" ~ -58.4432852,
      player == "Adrian Mannarino" ~ 2.3002885,
      player == "Tallon Griekspoor" ~ 4.6435597,
      player == "Sebastian Korda" ~ -82.5748194,
      player == "Jan Lennard Struff" ~ 8.3536824,
      player == "Alejandro Davidovich Fokina" ~ -4.2793767,
      player == "Lorenzo Musetti" ~ 10.096726,
      player == "Sebastian Baez" ~ -58.4432852,
      player == "Felix Auger Aliassime" ~ -73.5698065,
      player == "Tomas Martin Etcheverry" ~ -57.9537638,
      player == "Jiri Lehecka" ~ 14.9031301,
      player == "Alexander Bublik" ~ 30.1305083,
      player == "Laslo Djere" ~ 20.0901597,
      player == "Christopher Eubanks" ~ -84.3902644,
      player == "Aslan Karatsev" ~ 44.68211,
      player == "Arthur Fils" ~ 2.3805119,
      player == "Borna Coric" ~ 15.9772795,
      player == "Daniel Evans" ~ -1.9026911,
      player == "Roman Safiullin" ~ 37.5453056,
      player == "Alexei Popyrin" ~ 151.2082848,
      player == "Mackenzie Mcdonald" ~ -122.272863,
      player == "Andy Murray" ~ -4.2501687,
      player == "Sebastian Ofner" ~ 15.2721668,
      player == "Matteo Arnaldi" ~ 7.7748827,
      player == "Max Purcell" ~ 151.2082848,
      player == "Lorenzo Sonego" ~ 7.6824892,
      player == "Yoshihito Nishioka" ~ 136.5153283,
      player == "Alexander Shevchenko" ~ 39.7249086,
      player == "Stan Wawrinka" ~ 6.6327025,
      player == "Botic Van De Zandschulp" ~ 5.6662814,
      player == "Yannick Hanfmann" ~ 8.4034195,
      player == "Dusan Lajovic" ~ 20.4568974,
      player == "J J Wolf" ~ -84.5124602,
      player == "Miomir Kecmanovic" ~ 20.4568974,
      player == "Jordan Thompson" ~ 151.2082848,
      player == "Daniel Altmaier" ~ 6.4195011,
      player == "Roberto Bautista Agut" ~ -0.0377354,
      player == "Zhizhen Zhang" ~ 121.4691024,
      player == "Marton Fucsovics" ~ 21.7167982,
      player == "Marcos Giron" ~ -118.8375937,
      player == "Jack Draper" ~ -0.1736269,
      player == "Aleksandar Vukic" ~ 151.2082848,
      player == "Roberto Carballes Baena" ~ -16.2507843,
      player == "Fabian Marozsan" ~ 19.0402383,
      player == "Thanasi Kokkinakis" ~ 138.5999312,
      player == "Nuno Borges" ~ -8.6299982,
      player == "Pavel Kotov" ~ 37.6174782,
      player == "Christopher Oconnell" ~ 151.2082848,
      player == "Pedro Cachin" ~ -62.6888782,
      player == "Rinky Hijikata" ~ 151.2082848,
      player == "Borna Gojo" ~ 16.4399659,
      player == "Benjamin Bonzi" ~ 4.3600687,
      player == "Gael Monfils" ~ 2.320041,
      player == "Taro Daniel" ~ -74.0060152,
      player == "Richard Gasquet" ~ 3.2131307,
      player == "Dominik Koepfer" ~ 8.2073776,
      player == "Tomas Machac" ~ 14.0733907,
      player == "Thiago Seyboth Wild" ~ -51.33333,
      player == "Bernabe Zapata Miralles" ~ -0.3763353,
      player == "Alexandre Muller" ~ 2.0428293,
      player == "Cristian Garin" ~ -70.3211394,
      player == "Juan Pablo Varillas" ~ -77.0365256,
      player == "Gregoire Barrere" ~ 2.4853015,
      player == "Alejandro Tabilo" ~ -79.3839347,
      player == "Jaume Munar" ~ 3.1294799,
      player == "Constant Lestienne" ~ 2.2956951,
      player == "Federico Coria" ~ -60.6617024,
      player == "Albert Ramos" ~ 2.1774322,
      player == "Luca Van Assche" ~ 4.4256732,
      player == "Maximilian Marterer" ~ 11.077298,
      player == "Matteo Berrettini" ~ 12.4829321,
      player == "Daniel Elahi Galan" ~ -73.1182624,
      player == "Dominic Stricker" ~ 7.5631943,
      player == "Facundo Diaz Acosta" ~ -58.4432852,
      player == "Arthur Rinderknech" ~ 6.585476,
      player == "Alex Michelsen" ~ -117.7258122,
      player == "Dominic Thiem" ~ 16.2441166,
      player == "Yosuke Watanuki" ~ 139.6457957,
      player == "Quentin Halys" ~ 2.48291,
      player == "Emil Ruusuvuori" ~ 24.9427473,
      player == "Rafael Nadal" ~ 3.2106461,
      player == "Robin Soderling" ~ 14.2,
      player == "Roger Federer" ~ 7.5878261,
      player == "Tomas Berdych" ~ 17.971593,
      player == "David Ferrer" ~ 0.1634168,
      player == "Andy Roddick" ~ -95.9383758,
      player == "Fernando Verdasco" ~ -3.7035825,
      player == "Mikhail Youzhny" ~ 37.6063916,
      player == "Jurgen Melzer" ~ 16.3725042,
      player == "Jo-Wilfried Tsonga" ~ 0.1967849,
      player == "Marin Cilic" ~ 16.9797134,
      player == "Nicolas Almagro" ~ -1.1305431,
      player == "Mardy Fish" ~ -93.3501222,
      player == "Ivan Ljubicic" ~ 17.1917651,
      player == "Sam Querrey" ~ -122.4193286,
      player == "John Isner" ~ -79.7919754,
      player == "Marcos Baghdatis" ~ 33.0332657,
      player == "Nikolay Davydenko" ~ 38.4936475,
      player == "Michael Llodra" ~ 2.320041,
      player == "Ernests Gulbis" ~ 24.1051846,
      player == "Albert Montanes" ~ 0.5900091,
      player == "Juan Monaco" ~ -59.1356957,
      player == "David Nalbandian" ~ -64.3164639,
      player == "Viktor Troicki" ~ 20.4568974,
      player == "Juan Carlos Ferrero" ~ -0.6099929,
      player == "Thomaz Bellucci" ~ -48.450554,
      player == "Feliciano Lopez" ~ -4.0239568,
      player == "Guillermo Garcia Lopez" ~ -2.1581637,
      player == "Philipp Kohlschreiber" ~ 10.8979522,
      player == "Yen Hsun Lu" ~ 121.31143188476562,
      player == "Andrey Golubev" ~ 44.7519454,
      player == "Florian Mayer" ~ 11.5763079,
      player == "Juan Ignacio Chela" ~ -58.40231704711914,
      player == "Jarkko Nieminen" ~ 22.1,
      player == "Denis Istomin" ~ 69.2787079,
      player == "Gilles Simon" ~ 7.2683912,
      player == "Marcel Granollers" ~ 2.1774322,
      player == "Thiemo De Bakker" ~ 4.315730094909668,
      player == "Julien Benneteau" ~ 5.225506782531738,
      player == "Jeremy Chardy" ~ -0.3685668,
      player == "Sergiy Stakhovsky" ~ 30.5241361,
      player == "Potito Starace" ~ 14.7057054,
      player == "Alexandr Dolgopolov" ~ 30.5241361,
      player == "Janko Tipsarevic" ~ 20.4568974,
      player == "Tommy Robredo" ~ 2.6330963,
      player == "Victor Hanescu" ~ 26.10515022277832,
      player == "Andreas Seppi" ~ 11.3547399,
      player == "Benjamin Becker" ~ 6.6374902,
      player == "Lleyton Hewitt" ~ 138.599853515625,
      player == "Fabio Fognini" ~ 7.7748827,
      player == "Daniel Gimeno Traver" ~ -0.3763353,
      player == "Philipp Petzschner" ~ 11.5763079,
      player == "Michael Berrer" ~ 9.177595138549805,
      player == "Mikhail Kukushkin" ~ 44.5153353,
      player == "Xavier Malisse" ~ 3.2659884,
      player == "Kevin Anderson" ~ 28.041763305664062,
      player == "Radek Stepanek" ~ 18.5416556,
      player == "Pablo Cuevas" ~ -58.01738357543945,
      player == "Santiago Giraldo" ~ -75.6946778,
      player == "Robin Haase" ~ 4.315730094909668,
      player == "Carlos Berlocq" ~ -58.0138252,
      player == "Tobias Kamke" ~ 10.684738,
      player == "Fernando Gonzalez" ~ -70.6504502,
      player == "Florent Serra" ~ -0.5800364,
      player == "Pablo Andujar" ~ -2.1313528,
      player == "Pere Riba" ~ 2.1774322,
      player == "Ivo Karlovic" ~ 15.9772795,
      player == "Eduardo Schwank" ~ -60.6617024,
      player == "Dudi Sela" ~ 35.56822204589844,
      player == "Ricardo Mello" ~ -47.059564,
      player == "Ruben Ramirez Hidalgo" ~ -0.4881708,
      player == "Arnaud Clement" ~ 5.4474738,
      player == "Igor Andreev" ~ 37.6174782,
      player == "Teymuraz Gabashvili" ~ 44.8014495,
      player == "Illya Marchenko" ~ 34.6068797,
      player == "Mischa Zverev" ~ 37.6174782,
      player == "Rainer Schuettler" ~ 8.8426963,
      player == "Brian Dabul" ~ -58.54913330078125,
      player == "Michal Przysiezny" ~ 16.0935567,
      player == "Ricardas Berankis" ~ 25.289478302001953,
      player == "Ivan Dodig" ~ 16.9797134,
      player == "Lukas Lacko" ~ 17.8213848,
      player == "Marsel Ilhan" ~ 66.96456146240234,
      player == "Filippo Volandri" ~ 10.3402787,
      player == "Dustin Brown" ~ 10.081052,
      player == "Rui Machado" ~ -7.9351771,
      player == "Leonardo Mayer" ~ -57.812458,
      player == "Jan Hajek" ~ 17.251143,
      player == "Marcos Daniel" ~ -52.3966606,
      player == "Paul Henri Mathieu" ~ 7.7507127,
      player == "Kei Nishikori" ~ 133.048768,
      player == "Michael Russell" ~ -83.0466403,
      player == "Igor Kunitsyn" ~ 131.8855768,
      player == "Lukasz Kubot" ~ 15.5651049)) %>%
  reverse_geocode(lat = birth_lat, long = birth_long, method = "osm", full_results = TRUE) %>%
  select(rank_date, rank, player, player_id, hand, dob, ioc, height, age, birth_lat, birth_long, city, state, country) %>%
  mutate(
    birth_city = case_when(
      !is.na(birth_lat) & country == "United States" ~ str_c(city, ", ", state, ", ", country),
      !is.na(birth_lat) ~ str_c(city, ", ", country),
      player == "Milos Raonic" ~ "Podgorica, Montenegro",
      player == "David Goffin" ~ "Rocourt, Belgium",
      player == "Bernard Tomic" ~ "Stuttgart, Germany",
      player == "Benoit Paire" ~ "Avignon, France",
      player == "Jack Sock" ~ "Lincoln, Nebraska, United States",
      player == "Nick Kyrgios" ~ "Canberra, Australia",
      player == "Steve Johnson" ~ "Washington, D.C., United States",
      player == "Joao Sousa" ~ "Guimaraes, Portugal",
      player == "Gilles Muller" ~ "Luxembourg, Luxembourg",
      player == "Vasek Pospisil" ~ "Vernon, Canada",
      player == "Jiri Vesely" ~ "Příbram, Czechia",
      player == "Martin Klizan" ~ "Bratislava, Slovakia",
      player == "Aljaz Bedene" ~ "Ljubljana, Slovenia",
      player == "Donald Young" ~ "Chicago, Illinois, United States",
      player == "Hyeon Chung" ~ "Suwon-si, South Korea",
      player == "Federico Delbonis" ~ "Azul, Argentina",
      player == "Lukas Rosol" ~ "Brno, Czechia",
      player == "Victor Estrella" ~ "Santiago de los Caballeros, Dominican Republic",
      player == "Jerzy Janowicz" ~ "Łódź, Poland",
      player == "Simone Bolelli" ~ "Bologna, Italy",
      player == "Sam Groth" ~ "Narrandera, Australia",
      player == "Andreas Haider Maurer" ~ "Zwettl, Austria",
      player == "Pablo Carreno Busta" ~ "Gijón, Spain",
      player == "Paolo Lorenzi" ~ "Rome, Italy",
      player == "Denis Kudla" ~ "Kyiv, Ukraine",
      player == "Nicolas Mahut" ~ "Angers, France",
      player == "Inigo Cervantes Huegun" ~ "Hondarribia, Spain",
      player == "Guido Pella" ~ "Buenos Aires, Argentina",
      player == "Daniel Munoz de la Nava" ~ "Madrid, Spain",
      player == "Lucas Pouille" ~ "Grande-Synthe, France",
      player == "Andrey Kuznetsov" ~ "Tula, Russia",
      player == "Damir Dzumhur" ~ "Sarajevo, Bosnia and Herzegovina",
      player == "Steve Darcis" ~ "Liège, Belgium",
      player == "Diego Schwartzman" ~ "Buenos Aires, Argentina",
      player == "Rajeev Ram" ~ "Denver, CO",
      player == "Marco Cecchinato" ~ "Palermo, Italy",
      player == "Evgeny Donskoy" ~ "Moscow, Russia",
      player == "John Millman" ~ "Brisbane, Australia",
      player == "Yuki Bhambri" ~ "New Delhi, India",
      player == "Denis Shapovalov" ~ "Tel Aviv-Yafo, Israel",
      player == "Filip Krajinovic" ~ "Sombor, Serbia",
      player == "Reilly Opelka" ~ "St. Joseph, Michigan, United States",
      player == "Nikoloz Basilashvili" ~ "Tbilisi, Georgia",
      player == "Kyle Edmund" ~ "Johannesburg, South Africa",
      player == "Tennys Sandgren" ~ "Gallatin, Tennessee, United States",
      player == "Stefano Travaglia" ~ "Ascoli Piceno, Italy",
      player == "Salvatore Caruso" ~ "Avola, Italy",
      player == "Corentin Moutet" ~ "Neuilly-sur-Seine, France",
      player == "Egor Gerasimov" ~ "Minsk, Belarus",
      player == "Juan Ignacio Londero" ~ "Jesus Maria, Argentina",
      player == "Pierre Hugues Herbert" ~ "Schiltigheim, France",
      player == "Thiago Monteiro" ~ "Fortaleza, Ceará, Brazil",
      player == "Pedro Martinez" ~ "Alzira, Spain",
      player == "Lloyd Harris" ~ "Cape Town, South Africa",
      player == "Norbert Gombos" ~ "Galanta, Slovakia",
      player == "Attila Balazs" ~ "Budapest, Hungary",
      player == "Radu Albot" ~ "Chișinău, Moldova",
      player == "Mikael Ymer" ~ "Skara, Sweden",
      player == "Soon Woo Kwon" ~ "Sangju-si, South Korea",
      player == "Dennis Novak" ~ "Wiener Neustadt, Austria",
      player == "Gianluca Mager" ~ "Sanremo, Italy",
      player == "Mariano Navone" ~ "Nueve de Julio, Buenos Aires, Argentina",
      player == "Luciano Darderi" ~ "Villa Gesell, Argentina",
      player == "Flavio Cobolli" ~ "Rome, Italy",
      player == "Giovanni Mpetshi Perricard" ~ "Lyon, France",
      player == "Luca Nardi" ~ "Pesaro, Italy",
      player == "Jakub Mensik" ~ "Prostějov, Czechia",
      player == "Arthur Cazaux" ~ "Montpellier, France",
      player == "Brandon Nakashima" ~ "San Diego, California, United States",
      player == "Aleksandar Kovacevic" ~ "New York City, New York, United States",
      player == "Hugo Gaston" ~ "Toulouse, France",
      player == "Juncheng Shang" ~ "Beijing, China",
      player == "Sumit Nagal" ~ "Jhajjar, India",
      player == "Adam Walton" ~ "Brisbane, Australia",
      player == "Francisco Comesana" ~ "Mar del Plata, Buenos Aires, Argentina",
      player == "Gustavo Kuerten" ~ "Florianópolis, Brazil",
      player == "Marat Safin" ~ "Moscow, Russia",
      player == "Pete Sampras" ~ "Washington, D.C, United States",
      player == "Magnus Norman" ~ "Filipstad, Sweden",
      player == "Yevgeny Kafelnikov" ~ "Sochi, Russia",
      player == "Andre Agassi" ~ "Las Vegas, Nevada",
      player == "Alex Corretja" ~ "Barcelona, Spain",
      player == "Thomas Enqvist" ~ "Stockholm, Sweden",
      player == "Tim Henman" ~ "Oxford, United Kingdom",
      player == "Mark Philippoussis" ~ "Melbourne, Australia",
      player == "Wayne Ferreira" ~ "Johannesburg, South Africa",
      player == "Franco Squillari" ~ "Buenos Aires, Argentina",
      player == "Patrick Rafter" ~ "Mount Isa City, Australia",
      player == "Cedric Pioline" ~ "Neuilly-sur-Seine, France",
      player == "Dominik Hrbaty" ~ "Bratislava, Slovakia",
      player == "Sebastien Grosjean" ~ "Marseille, France",
      player == "Nicolas Kiefer" ~ "Holzminden, Germany",
      player == "Mariano Puerta" ~ "San Francisco, Argentina",
      player == "Sjeng Schalken" ~ "Weert, Netherlands",
      player == "Tommy Haas" ~ "Hamburg, Germany",
      player == "Nicolas Lapentti" ~ "Guayaquil, Ecuador",
      player == "Younes El Aynaoui" ~ "Rabat, Morocco",
      player == "Albert Costa" ~ "Lleida, Spain",
      player == "Andrei Pavel" ~ "Constanța, Romania",
      player == "Marc Rosset" ~ "Geneva, Switzerland",
      player == "Hicham Arazi" ~ "Casablanca, Morocco",
      player == "Fabrice Santoro" ~ "Tahiti, French Polynesia",
      player == "Michael Chang" ~ "Hoboken, New Jersey, United States",
      player == "Jan Michael Gambill" ~ "Spokane, Washington, United States",
      player == "Gaston Gaudio" ~ "Temperley, Argentina",
      player == "Byron Black" ~ "Harare, Zimbabwe",
      player == "Richard Krajicek" ~ "Rotterdam, Netherlands",
      player == "Marcelo Rios" ~ "Santiago, Chile",
      player == "David Prinosil" ~ "Olomouc, Czechia",
      player == "Thomas Johansson" ~ "Linköping, Sweden",
      player == "Max Mirnyi" ~ "Minsk, Belarus",
      player == "Carlos Moya" ~ "Palma, Spain",
      player == "Jerome Golmard" ~ "Dijon, France",
      player == "Gianluca Pozzi" ~ "Bari, Italy",
      player == "Jonas Bjorkman" ~ "Växjö, Sweden",
      player == "Vladimir Voltchkov" ~ "Minsk, Belarus",
      player == "Fernando Vicente" ~ "Benicarló, Spain",
      player == "Nicolas Escude" ~ "Chartres, France",
      player == "Francisco Clavet" ~ "Aranjuez, Spain",
      player == "Andrew Ilie" ~ "Bucharest, Romania",
      player == "Albert Portas" ~ "Barcelona, Spain",
      player == "Andreas Vinciguerra" ~ "Malmö Municipality, Sweden",
      player == "Jiri Novak" ~ "Prostejov, Czech Republic",
      player == "Stefan Koubek" ~ "Klagenfurt, Austria",
      player == "Todd Martin" ~ "Hinsdale, Illinois, United States",
      player == "Alex Calatrava" ~ "Cologne, Germany",
      player == "Karim Alami" ~ "Casablanca, Morocco",
      player == "Andrei Medvedev" ~ "Kyiv, Ukraine",
      player == "Harel Levy" ~ "Nahshonim, Israel",
      player == "Arnaud Di Pasquale" ~ "Casablanca, Morocco",
      player == "Mariano Zabaleta" ~ "Tandil, Argentina",
      player == "Agustin Calleri" ~ "Río Cuarto, Argentina",
      player == "Slava Dosedel" ~ "Prerov, Czech Republic",
      player == "Davide Sanguinetti" ~ "Viareggio, Italy",
      player == "Jason Stoltenberg" ~ "Narrabri, Australia",
      player == "Chris Woodruff" ~ "Knoxville, Tennessee, United States",
      player == "Olivier Rochus" ~ "Namur, Belgium",
      player == "Greg Rusedski" ~ "Montreal, Quebec, Canada",
      player == "Julien Boutter" ~ "Boulay, France",
      player == "Juan Balcells" ~ "Barcelona, Spain",
      player == "Markus Hantschk" ~ "Dachau, Germany",
      player == "Karol Kucera" ~ "Bratislava, Slovakia",
      player == "Christophe Rochus" ~ "Namur, Belgium",
      player == "Magnus Larsson" ~ "Olofström, Sweden",
      player == "Bohdan Ulihrach" ~ "Kolin, Czechia",
      player == "Jiri Vanek" ~ "Domazlice, Czechia",
      player == "Martin Damm" ~ "Liberec, Czechia",
      player == "Alberto Martin" ~ "Barcelona, Spain",
      player == "Mikael Tillstrom" ~ "Jonkoping, Sweden",
      player == "Paul Goldstein" ~ "Washington, D.C., United States",
      player == "Magnus Gustafsson" ~ "Lund, Sweden",
      player == "Wayne Arthurs" ~ "Adelaide, Australia",
      player == "Richard Fromberg" ~ "Ulverstone, Tasmania, Australia",
      player == "Sergi Bruguera" ~ "Barcelona, Spain",
      player == "Alexander Popp" ~ "Heidelberg, Germany",
      player == "Nicolas Massu" ~ "Viña del Mar, Chile",
      player == "Guillermo Coria" ~ "Rufino, Argentina",
      player == "David Sanchez" ~ "Zamora, Spain",
      player == "Justin Gimelstob" ~ "Livingston, New Jersey, United States",
      player == "Hyung Taik Lee" ~ "Hoengseong-gun, South Korea",
      player == "German Puentes" ~ "Barcelona, Spain",
      player == "Michel Kratochvil" ~ "Bern, Switzerland",
      player == "Sargis Sargsian" ~ "Yerevan, Armenia",
      player == "Raemon Sluiter" ~ "Rotterdam, Netherlands",
      player == "Michal Tabara" ~ "Uherske Hradiste, Czechia",
      player == "Daniel Elsner" ~ "Memmingerberg, Germany",
      player == "Felix Mantilla" ~ "Barcelona, Spain",
      player == "Fernando Meligeni" ~ "Buenos Aires, Argentina",
      player == "Stefan Edberg" ~ "Västervik, Sweden",
      player == "Boris Becker" ~ "Leimen, Germany",
      player == "Ivan Lendl" ~ "Ostrava, Czechia",
      player == "Andres Gomez" ~ "Guayaquil, Ecuador",
      player == "Thomas Muster" ~ "Leibnitz, Austria",
      player == "Emilio Sanchez" ~ "Madrid, Spain",
      player == "Goran Ivanisevic" ~ "Split, Croatia",
      player == "Brad Gilbert" ~ "Oakland, California, United States",
      player == "Jonas Svensson" ~ "Gothenburg, Sweden",
      player == "Andrei Chesnokov" ~ "Moscow, Russia",
      player == "John McEnroe" ~ "Wiesbaden, Germany",
      player == "Guillermo Perez Roldan" ~ "Tandil, Argentina",
      player == "Guy Forget" ~ "Casablanca, Morocco",
      player == "Jakob Hlasek" ~ "Prague, Czechia",
      player == "Jay Berger" ~ "Fort Dix, New Jersey, United States",
      player == "Juan Aguilera" ~ "Barcelona, Spain",
      player == "Aaron Krickstein" ~ "Ann Arbor, Michigan, United States",
      player == "Andrei Cherkasov" ~ "Ufa, Russia",
      player == "Richey Reneberg" ~ "Phoenix, Arizona, United States",
      player == "Alexander Volkov" ~ "Kaliningrad, Russia",
      player == "Jim Courier" ~ "Sanford, Florida, United States",
      player == "Horst Skoff" ~ "Klagenfurt am Wörthersee, Austria",
      player == "David Wheaton" ~ "Minneapolis, Minnesota, United States",
      player == "Ronald Agenor" ~ "Rabat, Morocco",
      player == "Henri Leconte" ~ "Lillers, France",
      player == "Amos Mansdorf" ~ "Tel Aviv-Yafo, Israel",
      player == "Karel Novacek" ~ "Prostějov, Czechia",
      player == "Franco Davin" ~ "Buenos Aires, Argentina",
      player == "Martin Jaite" ~ "Buenos Aires, Argentina",
      player == "Tim Mayotte" ~ "Springfield, Massachusetts, United States",
      player == "Petr Korda" ~ "Prague, Czechia",
      player == "Jordi Arrese" ~ "Barcelona, Spain",
      player == "Yannick Noah" ~ "Sedan, France",
      player == "Mats Wilander" ~ "Växjö, Sweden",
      player == "Michael Stich" ~ "Pinneberg, Germany",
      player == "Luiz Mattar" ~ "São Paulo, Brazil",
      player == "Scott Davis" ~ "Santa Monica, California, United States",
      player == "Omar Camporese" ~ "Bologna, Italy",
      player == "Carl Uwe Steeb" ~ "Aalen, Germany",
      player == "Derrick Rostagno" ~ "Los Angeles, California, United States",
      player == "Mark Koevermans" ~ "Rotterdam, Netherlands",
      player == "Marcelo Filippini" ~ "Montevideo, Uruguay",
      player == "Todd Woodbridge" ~ "Sydney, Australia",
      player == "Nicklas Kulti" ~ "Stockholm, Sweden",
      player == "Gary Muller" ~ "Durban, South Africa",
      player == "Wally Masur" ~ "Sydney, Australia",
      player == "Paul Haarhuis" ~ "Eindhoven, Netherlands",
      player == "Goran Prpic" ~ "Zagreb, Croatia",
      player == "Darren Cahill" ~ "Adelaide, Australia",
      player == "Todd Witsken" ~ "Indianapolis, Indiana, United States",
      player == "Thierry Champion" ~ "Bagnols-sur-Cèze, France",
      player == "Jimmy Arias" ~ "Grand Island, New York, United States",
      player == "Christo Van Rensburg" ~ "Uitenhage, South Africa",
      player == "Horacio De La Pena" ~ "Buenos Aires, Argentina",
      player == "Alex Antonitsch" ~ "Villach, Austria",
      player == "Peter Lundgren" ~ "Gudmundrå, Sweden",
      player == "Gilad Bloom" ~ "Tel Aviv, Israel",
      player == "Jean Philippe Fleurian" ~ "Paris, France",
      player == "Eric Jelen" ~ "Trier, Germany",
      player == "Veli Paloheimo" ~ "Tampere, Finland",
      player == "Javier Sanchez" ~ "Pamplona, Spain",
      player == "Kevin Curren" ~ "Durban, South Africa",
      player == "Jim Grabb" ~ "Tucson, Arizona, United States",
      player == "Anders Jarryd" ~ "Lidköping, Sweden",
      player == "Aki Rahunen" ~ "Helsinki, Finland",
      player == "Mark Kratzmann" ~ "Windera, Australia",
      player == "Tomas Carbonell" ~ "Barcelona, Spain",
      player == "Renzo Furlan" ~ "Conegliano, Italy",
      player == "Brad Pearce" ~ "Provo, Utah, United States",
      player == "Ramesh Krishnan" ~ "Chennai, India",
      player == "Christian Bergstrom" ~ "Gothenburg, Sweden",
      player == "Pat Cash" ~ "Melbourne, Australia",
      player == "Patrik Kuhnen" ~ "Püttlingen, Germany",
      player == "Marian Vajda" ~ "Považská Bystrica, Slovakia",
      player == "Guillaume Raoux" ~ "Bagnols-sur-Cèze, France",
      player == "Milan Srejber" ~ "Prague, Czechia",
      player == "Alexander Mronz" ~ "Cologne, Germany",
      player == "Jaime Yzaga" ~ "Lima, Peru",
      player == "Udo Riglewski" ~ "Lauffen am Neckar, Germany",
      player == "Robbie Weiss" ~ "Chicago, Illinois, United States",
      player == "Thomas Hogstedt" ~ "Mariestad, Sweden",
      player == "Grant Connell" ~ "Regina, Canada",
      player == "Malivai Washington" ~ "Glen Cove, New York, United States",
      player == "David Pate" ~ "Los Angeles, California, United States",
      player == "Brian Garrow" ~ "Santa Clara, California, United States",
      player == "Dan Goldie" ~ "Sioux City, Iowa, United States",
      player == "Cristiano Caratti" ~ "Acqui Terme, Italy",
      player == "Jan Gunnarsson" ~ "Olofström, Sweden",
      player == "Lars Jonsson" ~ "Goteborg, Sweden",
      player == "Kelly Evernden" ~ "Gisborne, New Zealand",
      player == "Bjorn Borg" ~ "Stockholm, Sweden",
      player == "Jimmy Connors" ~ "East St. Louis, Illinois, United States",
      player == "Guillermo Vilas" ~ "Mar del Plata, Argentina",
      player == "Gene Mayer" ~ "Flushing, New York, United States",
      player == "Harold Solomon" ~ "Silver Spring, Maryland, United States",
      player == "Jose Luis Clerc" ~ "Buenos Aires, Argentina",
      player == "Vitas Gerulaitis" ~ "Brooklyn, New York, United States",
      player == "Eliot Teltscher" ~ "Palos Verdes, California, United States",
      player == "Brian Gottfried" ~ "Baltimore, Maryland, United States",
      player == "Eddie Dibbs" ~ "Brooklyn, New York, United States",
      player == "Roscoe Tanner" ~ "Chattanooga, Tennessee, United States",
      player == "Wojtek Fibak" ~ "Poznań, Poland",
      player == "John Sadri" ~ "Charlotte, North Carolina, United States",
      player == "Victor Amaya" ~ "Grand Rapids, Michigan, United States",
      player == "Johan Kriek" ~ "Pongola, South Africa",
      player == "Vijay Amritraj" ~ "Chennai, India",
      player == "Brian Teacher" ~ "San Diego, California, United States",
      player == "Bob Lutz" ~ "San Clemente, California, United States",
      player == "Balazs Taroczy" ~ "Budapest, Hungary",
      player == "Corrado Barazzutti" ~ "Udine, Italy",
      player == "Tomas Smid" ~ "Pilsen, Czechia",
      player == "Bill Scanlon" ~ "Dallas, Texas, United States",
      player == "Heinz Gunthardt" ~ "Zürich, Switzerland",
      player == "Mel Purcell" ~ "Joplin, Missouri, United States",
      player == "Stan Smith" ~ "Pasadena, California, United States",
      player == "Victor Pecci" ~ "Asunción, Paraguay",
      player == "Jose Higueras" ~ "Palm Springs, California, United States",
      player == "Hans Gildemeister" ~ "Lima, Peru",
      player == "Adriano Panatta" ~ "Rome, Italy",
      player == "Mario Martinez" ~ "La Paz, Bolivia",
      player == "Phil Dent" ~ "Sydney, Australia",
      player == "Raul Ramirez" ~ "Ensenada, Mexico",
      player == "Kim Warwick" ~ "Sydney, Australia",
      player == "Peter Fleming" ~ "Chatham, New Jersey, United States",
      player == "Peter Mcnamara" ~ "Melbourne, Australia",
      player == "Rolf Gehring" ~ "Düsseldorf, Germany",
      player == "Paul Mcnamee" ~ "Dungannon, United Kingdom",
      player == "Vincent Van Patten" ~ "Bellerose, New York, United States",
      player == "Buster C Mottram" ~ "Wimbledon, England",
      player == "Rod Frawley" ~ "Brisbane, Australia",
      player == "Tim Gullikson" ~ "La Crosse, Wisconsin, United States",
      player == "Trey Waltke" ~ "St. Louis, Missouri, United States",
      player == "Butch Walts" ~ "Modesto, California, United States",
      player == "Andrew Pattison" ~ "Pretoria, South Africa",
      player == "Thomaz Koch" ~ "Porto Alegre, Brazil",
      player == "Christophe Roger-Vasselin" ~ "London, United Kingdom",
      player == "Sandy Mayer" ~ "Flushing, New York, United States",
      player == "Marcos Hocevar" ~ "Ijuí, Brazil",
      player == "Terry Moor" ~ "Hartford, Connecticut, United States",
      player == "Tom Gullikson" ~ "Lacrosse, Wisconsin, United States",
      player == "Colin Dibley" ~ "Sydney, Australia",
      player == "Manuel Orantes" ~ "Granada, Spain",
      player == "Chris Lewis" ~ "Auckland, New Zealand",
      player == "Bernie Mitton" ~ "Irvine, California, United States",
      player == "Pascal Portes" ~ "Villeneuve, France",
      player == "Hank Pfister" ~ "Bakersfield, California, United States",
      player == "Peter Rennert" ~ "Great Neck, New York, United States",
      player == "Carlos Kirmayr" ~ "São Paulo, Brazil",
      player == "Shlomo Glickstein" ~ "Rehovot, Israel",
      player == "Fernando Luna" ~ "Ciudad Real, Spain",
      player == "Pat Dupre" ~ "Liege, Belgium",
      player == "Fritz Buehning" ~ "Summit, New Jersey, United States",
      player == "Pavel Slozil" ~ "Opava, Czechia",
      player == "Jose Luis Damiani" ~ "Montevideo, Uruguay",
      player == "Tony Giammalva" ~ "Houston, Texas, United States",
      player == "Paolo Bertolucci" ~ "Forte Dei Marmi, Italy",
      player == "Ricardo Cano" ~ "Buenos Aires, Argentina",
      player == "Francisco Gonzalez" ~ "Wiesbaden, Germany",
      player == "Peter Feigl" ~ "Vienna, Austria",
      player == "Per Hjertquist" ~ "Bodafors, Sweden",
      player == "Ilie Nastase" ~ "Bucharest, Romania",
      player == "Ricardo Ycaza" ~ "Guayaquil, Ecuador",
      player == "Robert Vant Hof" ~ "Lynwood, California, United States",
      player == "Paul Kronk" ~ "Toowoomba, Queensland",
      player == "Sherwood Stewart" ~ "Baytown, Texas, United States",
      player == "Ferdi Taygan" ~ "Worcester, Massachusetts, United States",
      player == "Bruce Manson" ~ "Los Angeles, California, United States",
      player == "Gustavo Guerrero" ~ "Buenos Aires, Argentina",
      player == "Christophe Freyss" ~ "Strasbourg, France",
      player == "Zeljko Franulovic" ~ "Korčula, Croatia",
      player == "Angel Gimenez" ~ "Barcelona, Spain",
      player == "Kjell Johansson" ~ "Dalsjöfors, Sweden",
      player == "Richard Meyer" ~ "New York City, New York, United States",
      player == "Van Winitsky" ~ "Miami, Florida, United States",
      player == "Mark Edmondson" ~ "Gosford, Australia",
      player == "Marty Riessen" ~ "Hinsdale, Illinois, United States",
      player == "Nick Saviano" ~ "Teaneck, New Jersey, United States",
      player == "Gianni Ocleppo" ~ "Alba, Italy",
      player == "Tim Wilkison" ~ "Shelby, North Carolina",
      player == "Onny Parun" ~ "Wellington, New Zealand",
      player == "John Hayes" ~ "Canal Zone, Panama",
      player == "Eddie Edwards" ~ "Johannesburg, South Africa",
      player == "Dominique Bedel" ~ "Casablanca, Morocco",
      player == "John Alexander" ~ "Sydney, Australia",
      player == "Haroon Ismail" ~ "Harare, Zimbabwe",
      player == "John Newcombe" ~ "Sydney, Australia",
      player == "Tom Okker" ~ "Amsterdam, Netherlands",
      player == "Ken Rosewall" ~ "Sydney, Australia",
      player == "Rod Laver" ~ "Rockhampton City, Australia",
      player == "Jan Kodes" ~ "Prague, Czechia",
      player == "Arthur Ashe" ~ "Richmond, Virginia, United States",
      player == "Tom Gorman" ~ "Seattle, Washington, United States",
      player == "Roy Emerson" ~ "Blackbutt, Australia",
      player == "Nikola Pilic" ~ "Split, Croatia",
      player == "Roger Taylor" ~ "Sheffield, United Kingdom",
      player == "Jaime Fillol" ~ "Santiago, Chile",
      player == "Cliff Richey" ~ "San Angelo, Texas, United States",
      player == "Mark Cox" ~ "Leicester, United Kingdom",
      player == "Cliff Drysdale" ~ "Mbombela, South Africa",
      player == "Brian Fairlie" ~ "Christchurch, New Zealand",
      player == "Dick Stockton" ~ "New York City, New York, United States",
      player == "Karl Meiler" ~ "Erlangen, Germany",
      player == "Alex Metreveli" ~ "Tbilisi, Georgia",
      player == "Fred Stolle" ~ "Hornsby, Australia",
      player == "Hans Jurgen Pohmann" ~ "Cologne, Germany",
      player == "Erik Van Dillen" ~ "San Mateo, California, United States",
      player == "Patrick Proisy" ~ "Évreux, France",
      player == "Ross Case" ~ "Washington, D.C., United States",
      player == "Raymond Moore" ~ "Johannesburg, South Africa",
      player == "Jiri Hrebec" ~ "Teplice, Czechia",
      player == "Francois Jauffret" ~ "Bordeaux, France",
      player == "Jurgen Fassbender" ~ "Wesseling, Germany",
      player == "Charlie Pasarell" ~ "San Juan, Puerto Rico",
      player == "Clark Graebner" ~ "Cleveland, Ohio, United States",
      player == "Paul Gerken" ~ "New York City, New York, United States",
      player == "Dick Crealy" ~ "Sydney, Australia",
      player == "Geoff Masters" ~ "Brisbane, Queensland",
      player == "Ivan Molina" ~ "Bogota, Colombia",
      player == "Patrice Dominguez" ~ "Algiers, Algeria",
      player == "Ove Bengtson" ~ "Danderyd, Sweden",
      player == "Jeff Austin" ~ "Rolling Hills, California, United States",
      player == "Peter Szoke" ~ "Mosonszentjános, Hungary",
      player == "Allan Stone" ~ "Launceston, Australia",
      player == "Martin Mulligan" ~ "Marrickville, Australia",
      player == "Pierre Barthes" ~ "Béziers, France",
      player == "Barry Phillips Moore" ~ "Adelaide, Australia",
      player == "Boro Jovanovic" ~ "Zagreb, Croatia",
      player == "Gerald Battrick" ~ "Bridgend, United Kingdom",
      player == "Georges Goven" ~ "Lyon, France",
      player == "Juan Gisbert" ~ "Barcelona, Spain",
      player == "Antonio Zugarelli" ~ "Rome, Italy",
      player == "Frank Froehling" ~ "San Diego, California, United States",
      player == "Robert Maud" ~ "Johannesburg, South Africa",
      player == "Ion Tiriac" ~ "Brașov, Romania",
      player == "Mike Estep" ~ "Dallas, Texas, United States",
      player == "Jaime Pinto Bravo" ~ "Santiago, Chile",
      player == "Frew Mcmillan" ~ "Springs, South Africa",
      player == "Toshiro Sakai" ~ "Tokyo, Japan",
      player == "Bob Carmichael" ~ "Melbourne, Australia",
      player == "Ismail El Shafei" ~ "Cairo, Egypt",
      player == "Jeff Borowiak" ~ "Berkeley, California, United States",
      player == "Antonio Munoz" ~ "Barcelona, Spain",
      player == "Jean Baptiste Chanfreau" ~ "Sidi Ali Ben Youb, Algeria",
      player == "Hans Kary" ~ "Spittal, Austria",
      player == "John Cooper" ~ "Alexandra, Australia",
      player == "Milan Holecek" ~ "Pardubice, Czechia",
      player == "Ian Fletcher" ~ "Adelaide, Australia",
      player == "Wanaro N'Godrella" ~ "Nouméa, New Caledonia",
      player == "Vladimir Zednik" ~ "Prague, Czechia",
      player == "Haroon Rahim" ~ "Lahore, Pakistan",
      player == "Jeff Simpson" ~ "Hamilton, New Zealand",
      player == "John Paish" ~ "Croydon, United Kingdom",
      player == "Jun Kamiwazumi" ~ "Ishikawa, Japan",
      player == "Jim Mcmanus" ~ "Oakland, California",
      player == "Butch Seewagen" ~ "New York City, New York, United States",
      player == "Dick Dell" ~ "Washington, D.C., United States",
      player == "Patricio Cornejo" ~ "Llolleo, Chile",
      player == "John Lloyd" ~ "Leigh-on-Sea, United Kingdom",
      player == "Jannik Sinner" ~ "San Candido, Italy",
      player == "Stefanos Tsitsipas" ~ "Athens, Greece",
      player == "Grigor Dimitrov" ~ "Haskovo, Bulgaria",
      player == "Holger Rune" ~ "Gentofte, Denmark",
      player == "Tommy Paul" ~ "Voorhees Township, New Jersey, United States",
      player == "Ben Shelton" ~ "Atlanta, Georgia, United States",
      player == "Adrian Mannarino" ~ "Soisy-sous-Montmorency, France",
      player == "Jiri Lehecka" ~ "Mlada Boleslav, Czechia",
      player == "Frances Tiafoe" ~ "Hyattsville, Maryland, United States",
      player == "Lorenzo Musetti" ~ "Carrara, Italy",
      player == "Alejandro Davidovich Fokina" ~ "Rincón de la Victoria, Spain",
      player == "Matteo Arnaldi" ~ "Sanremo, Italy",
      player == "Tomas Machac" ~ "Beroun, Czechia",
      player == "Arthur Fils" ~ "Bondoufle, France",
      player == "Jan Lennard Struff" ~ "Warstein, Germany",
      player == "Sebastian Ofner" ~ "Bruck an der Mur, Austria",
      player == "Thiago Seyboth Wild" ~ "Marechal Cândido Rondon, Brazil",
      player == "Alex Michelsen" ~ "Aliso Viejo, California, United States",
      player == "Jaume Munar" ~ "Santanyí, Spain",
      player == "Dominik Koepfer" ~ "Furtwangen, Germany",
      player == "Arthur Rinderknech" ~ "Gassin, France",
      player == "Daniel Altmaier" ~ "Kempen, Germany",
      player == "Alexandre Muller" ~ "Poissy, France",
      player == "Fabio Fognini" ~ "Sanremo, Italy",
      .default = NA)) %>%
  geocode(birth_city, method = 'osm', lat = new_lat, long = new_long) %>%
  mutate(
    birth_lat = if_else(is.na(birth_lat), new_lat, birth_lat),
    birth_long = if_else(is.na(birth_long), new_long, birth_long)) %>%
  select(-contains("new"), -state, -country, -city)

# write_csv(rankings_100, here("data/atp_rankings_top100"))