---
title: "Country"
---

This page aggregates each players' success by the country the represent. For the table below, countries are not penalized for losses.

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  comment = "#", fig.height = 3, 
  cache = FALSE, collapse = TRUE,
  error = TRUE, echo = FALSE,
  message = FALSE,
  warning = FALSE)
```

```{r load, include = FALSE}
library("tidyverse"); theme_set(theme_minimal())
library("here")
library("flextable")
library("plotly")

matches <- read_csv(here("data/gs_matches.csv"))
players <- read_csv(here("data/gs_players.csv"))

set_flextable_defaults(
  font.size = 10, theme_fun = theme_zebra,
  padding = 3,
  background.color = "#EFEFEF",
  text.align = "center")
```

```{r table 1}
#| tbl-cap: All Time Country Rankings
players %>%
  group_by(ioc) %>%
  summarize(
    `Total Points` = sum(if_else(points > 0 , points, 0)) + sum(bonus),
    `Victory Points` = sum(if_else(points > 0 , points, 0)),
    `Bonus Points` = sum(bonus),
    `Australian Open` = sum(if_else(tourney_name == "Australian Open" & points > 0, points + bonus, 0)),
    `French Open` = sum(if_else(tourney_name == "Roland Garros" & points > 0, points + bonus, 0)),
    `Wimbledon` = sum(if_else(tourney_name == "Wimbledon" & points > 0, points + bonus, 0)),
    `US Open` = sum(if_else(tourney_name == "US Open" & points > 0, points + bonus, 0)),
    Victories = sum(points > 0),
    `Win Percent` = scales::percent(sum(points > 0)/(sum(points > 0) + sum(points < 0)), accuracy = .01)) %>%
  ungroup() %>%
  rename(
    Country = ioc) %>%
  arrange(desc(`Total Points`)) %>%
  mutate(
    Rank = row_number()) %>%
  relocate(Rank, .before = Country) %>%
  slice(1:25) %>%
  flextable() %>%
  align(align = "center", part = "all") %>%
  width(j = 1, width = .6) %>%
  width(j = c(3:9,11), width = 1.2) %>%
  colformat_double(j = c(3,4,5,6,7,8,9), digits = 0) %>%
  width(j = 2, width = 2)
```

```{r}
#| tbl-cap: Country Rankings by Grand Slam Results
players %>%
  group_by(ioc) %>%
  summarize(
    Titles = sum(result == "winner" & round == "F"),
    Finals = sum(round == "F"),
    Semis = sum(round == "SF"),
    Quarters = sum(round == "QF")) %>%
  arrange(desc(Titles), desc(Finals), desc(Semis), desc(Quarters)) %>%
  ungroup() %>%
  mutate(
    Rank = row_number()) %>%
  rename(
    Country = ioc) %>%
  relocate(Rank, .before = Country) %>%
  slice(1:25) %>%
  flextable() %>%
  align(align = "center", part = "all") %>%
  width(j = c(1:6), width = 1) %>%
  width(j = 2, width = 1.6)
```

```{r, fig.height = 7, fig.width = 12}
#| fig-cap: Countries over Time
country_sum <- players %>%
  group_by(ioc) %>%
  summarize(
    `Total Points` = sum(if_else(points > 0 , points, 0)) + sum(bonus),
    `Victory Points` = sum(if_else(points > 0 , points, 0)),
    `Bonus Points` = sum(bonus),
    `Australian Open` = sum(if_else(tourney_name == "Australian Open" & points > 0, points + bonus, 0)),
    `French Open` = sum(if_else(tourney_name == "Roland Garros" & points > 0, points + bonus, 0)),
    `Wimbledon` = sum(if_else(tourney_name == "Wimbledon" & points > 0, points + bonus, 0)),
    `US Open` = sum(if_else(tourney_name == "US Open" & points > 0, points + bonus, 0)),
    Victories = sum(points > 0),
    `Win Percent` = scales::percent(sum(points > 0)/(sum(points > 0) + sum(points < 0)), accuracy = .01)) %>%
  ungroup() %>%
  arrange(desc(`Total Points`))

top10 <- country_sum %>% ungroup() %>% slice(1:10) %>% select(ioc) %>% pull()
top20 <- country_sum %>% ungroup() %>% slice(1:20) %>% select(ioc) %>% pull()
top25 <- country_sum %>% ungroup() %>% slice(1:25) %>% select(ioc) %>% pull()
top30 <- country_sum %>% ungroup() %>% slice(1:30) %>% select(ioc) %>% pull()
top50 <- country_sum %>% ungroup() %>% slice(1:50) %>% select(ioc) %>% pull()

# top players over time
p <- players %>%
  mutate(points_revision = if_else(points > 0, points, 0)) %>%
  group_by(ioc) %>%
  mutate(
    `Total Points` = cumsum(points_revision + bonus)) %>%
  filter(ioc %in% top25) %>%
  rename(
    Country = ioc,
    Date = date) %>%
  ungroup() %>%
  ggplot(aes(x = Date, y = `Total Points`, color = Country)) +
  geom_line() +
  scale_x_date(expand = c(0, 1000)) +
  theme(legend.position = "none")

ggplotly(p)
```

```{r top country without a grand slam}
#| tbl-cap: Top Countries without a Grand Slam
players %>%
  group_by(ioc) %>%
  summarize(
    `Total Points` = sum(if_else(points > 0 , points, 0)) + sum(bonus),
    `Victory Points` = sum(if_else(points > 0 , points, 0)),
    `Bonus Points` = sum(bonus),
    Titles = sum(result == "winner" & round == "F"),
    Finals = sum(round == "F"),
    Semis = sum(round == "SF"),
    Victories = sum(points > 0),
    Defeats = sum(points < 0),
    `Win Percent` = scales::percent(Victories/(Victories + Defeats), accuracy = .01)) %>%
  ungroup() %>%
  rename(
    Country = ioc) %>%
  filter(Titles == 0) %>%
  arrange(desc(`Total Points`)) %>%
  mutate(
    Rank = row_number()) %>%
  relocate(Rank, .before = Country) %>%
  select(-Titles) %>%
  slice(1:10) %>% 
  flextable() %>%
  align(align = "center", part = "all") %>%
  width(j = c(3:5, 10), width = 1) %>%
  width(j = c(1,6:9), width = .7) %>%
  width(j = 2, width = 1.6)
```





