---
title: "Rankings"
---

This page ranks the top players overall and shows the best players without a Grand Slam title.

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  comment = "#", fig.height = 3, 
  cache = FALSE, collapse = TRUE,
  error = TRUE, echo = FALSE,
  message = FALSE,
  warning = FALSE)
```

```{r load, include = FALSE}
library("tidyverse"); theme_set(theme_minimal())
library("here")
library("flextable")

matches <- read_csv(here("data/gs_matches.csv"))
players <- read_csv(here("data/gs_players.csv"))

set_flextable_defaults(
  font.size = 10, theme_fun = theme_zebra,
  padding = 3,
  background.color = "#EFEFEF",
  text.align = "center")
```

```{r table 1}
#| tbl-cap: All Time Rankings
players %>%
  group_by(name, dob, ioc) %>%
  summarize(
    `Total Points` = sum(points) + sum(bonus),
    `Victory Points` = sum(points),
    `Bonus Points` = sum(bonus),
    Victories = sum(points > 0),
    Defeats = sum(points < 0),
    `Win Percent` = scales::percent(Victories/(Victories + Defeats), accuracy = .01)) %>%
  ungroup() %>%
  rename(
    Country = ioc,
    Name = name) %>%
  arrange(desc(`Total Points`)) %>%
  mutate(
    Rank = row_number(),
    `Birth Year` = year(dob)) %>%
  relocate(Rank, .before = Name) %>%
  relocate(`Birth Year`, .before = Country) %>%
  select(-dob) %>%
  slice(1:25) %>%
  flextable() %>%
  align(align = "center", part = "all") %>%
  width(j = 10, width = 1.3) %>%
  width(j = 2, width = 2.2) %>%
  width(j = 4, width = 1.6) %>%
  width(j = c(1,3,8:10), width = .6) %>%
  colformat_double(j = c(5,6,7,8,9), digits = 0) %>%
  colformat_double(j = 3,
    big.mark = "", digits = 0, na_str = "N/A")
```

```{r}
#| tbl-cap: Player Rankings by Grand Slam Results
players %>%
  group_by(name, dob, ioc) %>%
  summarize(
    Titles = sum(result == "winner" & round == "F"),
    Finals = sum(round == "F"),
    Semis = sum(round == "SF"),
    Quarters = sum(round == "QF"),
    "4th Round" = sum(round == "R16"),
    "3rd Round" = sum(round == "R32"),
    "2nd Round" = sum(round == "R64"),
    "1st Round" = sum(round == "R128")) %>%
  arrange(desc(Titles), desc(Finals), desc(Semis), desc(Quarters),
          desc(`4th Round`), desc(`3rd Round`), desc(`2nd Round`), desc(`1st Round`)) %>%
  ungroup() %>%
  mutate(
    Rank = row_number(),
    `Birth Year` = year(dob)) %>%
  relocate(Rank, .before = name) %>%
  rename(
    Country = ioc,
    Name = name) %>%
  relocate(`Birth Year`, .before = Country) %>%
  select(-dob) %>%
  slice(1:25) %>%
  flextable() %>%
  align(align = "center", part = "all") %>%
  width(j = 2, width = 2) %>%
  width(j = 4, width = 1.6) %>%
  width(j = 1, width = .6) %>%
  width(j = c(5:12), width = .8) %>%
  colformat_double(j = 3,
    big.mark = "", digits = 0, na_str = "N/A")
```

```{r top players without a grand slam}
#| tbl-cap: Top Players without a Grand Slam
players %>%
  group_by(name, dob, ioc) %>%
  # group_by(name) %>%
  summarize(
    `Total Points` = sum(points) + sum(bonus),
    `Victory Points` = sum(points),
    `Bonus Points` = sum(bonus),
    Titles = sum(round == "F" & result == "winner"),
    Finals = sum(round == "F"),
    Victories = sum(points > 0),
    Defeats = sum(points < 0),
    `Win Percent` = scales::percent(Victories/(Victories + Defeats), accuracy = .01)) %>%
  ungroup() %>%
  rename(
    Country = ioc,
    Name = name) %>%
  filter(Titles == 0) %>%
  arrange(desc(`Total Points`)) %>%
  mutate(
    Rank = row_number(),
    `Birth Year` = year(dob)) %>%
  relocate(Rank, .before = Name) %>%
  relocate(`Birth Year`, .before = Country) %>%
  select(-dob, -Titles) %>%
  slice(1:25) %>% 
  flextable() %>%
  align(align = "center", part = "all") %>%
  width(j = 2, width = 2.2) %>%
  width(j = 4, width = 1.6) %>%
  width(j = c(1,3,8:11), width = .6) %>%
  colformat_double(j = c(5:9), digits = 0) %>%
  colformat_double(j = 3,
    big.mark = "", digits = 0, na_str = "N/A")
```


